<?php

namespace AppBundle\Repository;

/**
 * FriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsRepository extends \Doctrine\ORM\EntityRepository
{
}
